### ISSUE TITLE
Exception while clicking on Stats button on Home Screen

### ISSUE THREAD

**Issue by Gaurav-Srivastava88** [cryspuwaterloo/privacyguard#24]
I installed the app and started VPN. After one leak from an app I clicked on stats button and the app crashed. Please find attached the stacktrace.
[StackTrace.txt](https://github.com/cryspuwaterloo/privacyguard/files/1443892/StackTrace.txt)

**Comment by uhengart** [comment]
Thanks for reporting. This should be fixed now.
